/// <auto-generated />
namespace LMobile.Gen3LicenseManagement.Dao.BusinessObjects {
	public partial class StoredModuleProperty : StoredObject {
		public virtual string PropertyName { get; set; }
		public virtual string Description { get; set; }
	}
}
