/// <auto-generated />
using System;
namespace LMobile.Gen3LicenseManagement.Dao.BusinessObjects {
	public partial class StoredModule : StoredObject {
		public virtual string ProjectType { get; set; }
		public virtual Guid ModuleGuid { get; set; }
		public virtual string ModuleName { get; set; }
		public virtual string Description { get; set; }
	}
}
