/// <auto-generated />
using LMobile.Gida;
namespace LMobile.Gen3LicenseManagement.Dao.Mapping {
	public partial class StoredModulePropertyMapping : StoredObjectMapping {
		public readonly global::LMobile.Gida.GidaColumnMapping PropertyName;
		public readonly global::LMobile.Gida.GidaColumnMapping Description;
		public StoredModulePropertyMapping(global::LMobile.Gida.GidaSession session)
			: base(session, "ModuleProperty") {
			this.OnConstructing();
			var define = this.Define<global::LMobile.Gen3LicenseManagement.Dao.BusinessObjects.StoredModuleProperty>();
			this.PropertyName = define.Column("PropertyName", 32, o => o.PropertyName, (o, value) => o.PropertyName = value);
			this.Description = define.Column("Desription", 64, o => o.Description, (o, value) => o.Description = value);
			this.OnConstructed();
		}
		protected override void DefineSchema(GidaTableMappingSchemaDefinition define) {
			base.DefineSchema(define);
			define.UniqueIndex("ModuleProperty_I1", this.PropertyName, this.Description);
		}
		partial void OnConstructing();
		partial void OnConstructed();
	}
}
