/// <auto-generated />
namespace LMobile.Gen3LicenseManagement.Dao.Mapping {
	public partial class StoredInstallationTypeMapping : global::LMobile.Gida.GidaTableMapping {
		public readonly global::LMobile.Gida.GidaColumnMapping InstallationType;
		public StoredInstallationTypeMapping(global::LMobile.Gida.GidaSession session)
			: base(session, "InstallationType") {
			this.OnConstructing();
			var define = this.Define<global::LMobile.Gen3LicenseManagement.Dao.BusinessObjects.StoredInstallationType>();
			this.InstallationType = define.Column("InstallationType", 32, o => o.InstallationType, (o, value) => o.InstallationType = value, global::LMobile.Gida.GidaTableColumn.PrimaryKey);
			this.OnConstructed();
		}
		partial void OnConstructing();
		partial void OnConstructed();
	}
}
