/// <auto-generated />
using LMobile.Gida;

namespace LMobile.Gen3LicenseManagement.Dao.Mapping {
	public partial class StoredModulePropertiesInModulesMapping : StoredObjectMapping {
		public readonly global::LMobile.Gida.GidaColumnMapping ModuleID;
		public readonly global::LMobile.Gida.GidaColumnMapping ModulePropertyID;
		public StoredModulePropertiesInModulesMapping(global::LMobile.Gida.GidaSession session)
			: base(session, "ModulePropertiesInModules") {
			this.OnConstructing();
			var define = this.Define<global::LMobile.Gen3LicenseManagement.Dao.BusinessObjects.StoredModulePropertiesInModules>();
			this.ModuleID = define.Column("ModuleID", o => o.ModuleID, (o, value) => o.ModuleID = value);
			this.ModulePropertyID = define.Column("ModulePropertyID", o => o.ModulePropertyID, (o, value) => o.ModulePropertyID = value);
			this.OnConstructed();
		}
		protected override void DefineSchema(GidaTableMappingSchemaDefinition define) {
			base.DefineSchema(define);
			define.UniqueIndex("ModulePropertiesInModules_I1", this.ModuleID, this.ID);
			define.ForeignKey<StoredModuleMapping>("ModulePropertiesInModules_FK1", (f, add) => add.Column(this.ModuleID, f.ID));
			define.ForeignKey<StoredModulePropertyMapping>("ModulePropertiesInModules_FK2", (f, add) => add.Column(this.ModulePropertyID, f.ID));
		}
		partial void OnConstructing();
		partial void OnConstructed();
	}
}
