/// <auto-generated />
namespace LMobile.Gen3LicenseManagement.Dao.Mapping {
	public partial class StoredProjectTypeMapping : global::LMobile.Gida.GidaTableMapping {
		public readonly global::LMobile.Gida.GidaColumnMapping ProjectType;
		public StoredProjectTypeMapping(global::LMobile.Gida.GidaSession session)
			: base(session, "ProjectType") {
			this.OnConstructing();
			var define = this.Define<global::LMobile.Gen3LicenseManagement.Dao.BusinessObjects.StoredProjectType>();
			this.ProjectType = define.Column("ProjectType", 32, o => o.ProjectType, (o, value) => o.ProjectType = value, global::LMobile.Gida.GidaTableColumn.PrimaryKey);
			this.OnConstructed();
		}
		partial void OnConstructing();
		partial void OnConstructed();
	}
}
